/**
 * Constants for Recipe Editor component
 */

export const EDITOR_CONSTANTS = {
  // Debounce times (ms)
  AUTO_SAVE_DEBOUNCE_MS: 3000,
  PREVIEW_UPDATE_DEBOUNCE_MS: 50,
  AUTOCOMPLETE_DEBOUNCE_MS: 150,
  AUTOCOMPLETE_CLOSE_DELAY_MS: 200,
  IMAGE_NAME_UPDATE_DEBOUNCE_MS: 1000,
  TOOLTIP_HIDE_DELAY_MS: 300,

  // UI display limits
  TITLE_MAX_LENGTH_TOOLTIP: 50,
  TITLE_MAX_LENGTH_EXPORT: 60,
  MAX_TOOLTIP_ITEMS: 10,
  MAX_ERROR_MESSAGES_SHOWN: 3,

  // Validation
  MAX_FILE_SIZE_MB: 10,
} as const;
